"""hammad.cli._rich"""

from ._utils import (
    wrap_renderable_with_rich_config,
    get_rich_console,
    has_rich_handler,
    create_rich_handler,
    update_rich_handler,
    create_rich_logger,
    update_rich_logger,
    run_rich_live,
)
from ._types import (
    RichConsole,
    RichPanel,
    RichLive,
    RichText,
    RichStyle,
    RichColorType,
    RichHandler,
    RichBackgroundType,
    RichRenderableType,
    RichColorHex,
    RichColorTuple,
    RichColorName,
    RichStyleSettings,
    RichTextSettings,
    RichBackgroundSettings,
    RichRenderableSettings,
    RichLiveSettings,
    RichLoggingLevelSettings,
    RichLoggingSettings,
    RichDefaultLoggingLevelSettings,
    RichStyleType,
)

__all__ = (
    # Utils
    "wrap_renderable_with_rich_config",
    "get_rich_console",
    "run_rich_live",
    "has_rich_handler",
    "create_rich_handler",
    "update_rich_handler",
    "create_rich_logger",
    "update_rich_logger",
    # Types
    "RichHandler",
    "RichColorType",
    "RichConsole",
    "RichPanel",
    "RichLive",
    "RichText",
    "RichStyle",
    "RichBackgroundType",
    "RichRenderableType",
    "RichColorHex",
    "RichColorTuple",
    "RichColorName",
    "RichStyleSettings",
    "RichTextSettings",
    "RichBackgroundSettings",
    "RichRenderableSettings",
    "RichLiveSettings",
    "RichLoggingLevelSettings",
    "RichLoggingSettings",
    "RichDefaultLoggingLevelSettings",
    "RichStyleType",
)
